name: Auto-release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Create a new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          
      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        with:
          latest: true
          # Tag name start with `v`
          pattern: '^v.*'
          # Including pre-release
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if git tag points to a version
        id: check_git_tag
        run: |
          if git tag --points-at HEAD | grep -q "^v"; then
            echo "git_head_valid=true" >> $GITHUB_OUTPUT
            echo "git is not pointing to a version."
          else
            echo "git_head_valid=false" >> $GITHUB_OUTPUT
            echo "git is pointing to the version:"
            git tag --points-at HEAD
          fi
      
      - name: Check if already released
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
        id: check_release
        run: |
          CURRENT_COMMIT_TAG=$(git tag --points-at HEAD)
          echo "Current release: ${{ steps.get_current_release.outputs.tag_name }}"
          echo "Current commit: $CURRENT_COMMIT_TAG"
          if test "${{ steps.get_current_release.outputs.tag_name }}"= $CURRENT_COMMIT_TAG; then
            echo "already_released=true" >> $GITHUB_OUTPUT
            echo "This commit already has a released tag. Will skip release."
          else
            echo "already_released=false" >> $GITHUB_OUTPUT
            echo "No release found. Proceeding with release."
          fi

      - name: Setup Python environment
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
          && steps.check_release.outputs.already_released == 'false'
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install uv
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
          && steps.check_release.outputs.already_released == 'false'
        uses: astral-sh/setup-uv@v7

      - name: Ensure repo status is clean
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
          && steps.check_release.outputs.already_released == 'false'
        run: git status

      - name: Build package
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
          && steps.check_release.outputs.already_released == 'false'
        run: uv build

      - name: Get version number from uv
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
          && steps.check_release.outputs.already_released == 'false'
        run: echo "version_number=$(uv version --short | tr -d ' \n')" >> $GITHUB_ENV

      - name: Display new version number
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
          && steps.check_release.outputs.already_released == 'false'
        run: |
          echo "version_number: v${{ env.version_number }}"

      - name: Create release in GitHub repo
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
          && steps.check_release.outputs.already_released == 'false'
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.version_number }}

      - name: Publish package (trusted publishing)
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
          && steps.check_release.outputs.already_released == 'false'
        run: uv publish --trusted-publishing always

      - name: Ensure complete
        if: steps.check_git_tag.outputs.git_head_valid == 'true'
          && steps.check_release.outputs.already_released == 'false'
        run: echo "Auto-release complete!"
